sudo: required
services:
  - docker

before_install:
  - docker build -t justinxcguo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run justinxcguo/react-test npm test -- --coverage

after_success:
  - docker build -t justinxcguo/multi-client ./client
  - docker build -t justinxcguo/multi-nginx ./nginx
  - docker build -t justinxcguo/multi-server ./server
  - docker build -t justinxcguo/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push to docker hub
  - docker push justinxcguo/multi-client
  - docker push justinxcguo/multi-nginx
  - docker push justinxcguo/multi-server
  - docker push justinxcguo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env:  MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-460278743514
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
